# Generated by Django 4.0.5 on 2022-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0004_formacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='descripcion',
            field=models.CharField(max_length=600),
        ),
    ]
